# Generated by Django 4.1.7 on 2023-03-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(max_length=100, verbose_name="API Provider"),
                ),
                ("api_key", models.CharField(max_length=100, verbose_name="API Key")),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template", models.TextField(verbose_name="Prompt Template")),
                ("input_variables", models.CharField(max_length=4096, verbose_name="")),
            ],
        ),
    ]
