# Generated by Django 4.1.7 on 2023-03-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0003_openaichatquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="num_input_vars",
            field=models.IntegerField(
                default=0, verbose_name="Number of Input Variables"
            ),
        ),
    ]
