# Generated by Django 4.1.7 on 2023-03-27 01:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0004_prompt_num_input_vars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openaichatquery",
            name="query_response",
        ),
        migrations.AddField(
            model_name="openaichatquery",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="openaichatquery",
            name="api",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="llm.modelproviderapi",
            ),
        ),
    ]
