# Generated by Django 4.1.7 on 2023-03-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0006_remove_prompt_input_variables_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelproviderapi",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="openaichatquery",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
