# Generated by Django 4.1.7 on 2023-03-29 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0007_alter_modelproviderapi_id_alter_openaichatquery_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openaichatquery",
            name="memory",
        ),
    ]
